spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1038731093546-eg4ur0qjetu5fcfchp6lhjmn7gelsm4p.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: localhost:4200/login
            scope:
              - email
              - profile
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      enabled: false
      data-locations: classpath:sql-init.sql
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8092

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8091/eureka/
  instance:
    preferIpAddress: true
    nonSecurePort: 8081
